### ISSUE TITLE
Code problem

### ISSUE THREAD

**Issue by a649473624** [wujrtudou/AdaptiveFireflyAlgorithm#1]

**Comment by liugx1997** [comment]
> Dear teacher, can I use your code to publish papers in other aspects?

**Comment by wujrtudou** [comment]
yes













At 2021-11-17 00:55:13, "liugx1997" ***@***.***> wrote:

Dear teacher, can I use your code to publish papers in other aspects?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
